### ISSUE TITLE
bei der neuesten version startet das spiel nicht nach voting

### ISSUE THREAD

**Issue by svenlr** [Machplatzwennduunsaufderstrassesiehst/Mental#16]
habe mit 2 spieler die neueste version getestet, allerdings endet das voting leider nicht, und man kommt nicht ins spiel

**Comment by m1a9l9t7e** [comment]
willst du das issue dann closen or naw ?@soeiner

**Comment by svenlr** [comment]
ist es denn schon gelöst? @m1a9l9t7e 
also ich habe es noch nicht gefunden
