### ISSUE TITLE
kein sync der Branch

### ISSUE THREAD

**Issue by exlo89** [Machplatzwennduunsaufderstrassesiehst/Mental#19]
Moin Jungs
Ich bin hier gerade am ausprobieren. Sagt mal wieso synchronisiert der nicht meine Branch, die ich auf mein Festrechner erstellt habe (bin an meinem Laptop). Ich hab ja die Brench hochgeladen, also müsstet ihr die auch sehen. Online seh ich die Branch auch, aber der synct das nicht.
Habt ihr eine Ahnung warum das so ist. 

fette Grüße
der Seelelose

**Comment by svenlr** [comment]
Also ich erstelle branches immer auf github direkt, und nicht lokal auf meinem Rechner, das geht auf jeden Fall :D

**Comment by m1a9l9t7e** [comment]
weil deine branch erst wieder zum master zurückgeführt werden müsste. Das kannst du machen indem du sie mergst. Die updates an denen wir arbeiten/gearbeitet haben sollten das was du tust aber eig. auch garnicht beeinflußen. Du kannst also eigentlich unbesorgt offline weiterarbeiten

**Comment by m1a9l9t7e** [comment]
wenn du gerne auf dem neusten stand seien willst könntest du auch einfach ne neue branch anlegen und das was du gemacht hast da rein kopieren. Dann änderst du nichts an der Master Branch
