### ISSUE TITLE
Status Bar bei mehreren gameModes?

### ISSUE THREAD

**Issue by svenlr** [Machplatzwennduunsaufderstrassesiehst/Mental#22]
Wir könnten dieses Statusleiste mit Rot / Grün ja auch für mehrere gameModes nutzen, indem sie anzeigen, wie weit man Prozentual vom Sieg entfernt ist / wie viele Punkte Vorsprung man zum nächsten hat?
@m1a9l9t7e

**Comment by m1a9l9t7e** [comment]
Wäre möglich, für die anderen gamemodes fände ich es aber noch cooler wenn
es so eine art vidualisierung des scorevoards wäre. Jeder Spieler hat
seinen eigenen Balken. Und der füllt sich je nach fortschritt auf. Dann
kann man sehen wer gerade führt usw.

=> Hab ich mir auch schon überlegt, wobei vllt so richtig verpeilte faces auch irgendwie lustig wären

**Comment by m1a9l9t7e** [comment]
kannst du mal die Website aktualisieren ? ;
Außerdem:
Hab gerade beim Versuch zu diesen Error bekommen : 
communication.js:80 WebSocket connection to 'ws://192.168.1.35:1297/' failed: Error in connection establishment: net::ERR_CONNECTION_TIMED_OUT
@soeiner

**Comment by svenlr** [comment]
hab aktualisiert

**Comment by m1a9l9t7e** [comment]
status bar und shop info sehen sehr nice aus :+1:
