### ISSUE TITLE
beatbob bounty: bob beaten bounty

### ISSUE THREAD

**Issue by svenlr** [Machplatzwennduunsaufderstrassesiehst/Mental#23]
Sollten die Spieler vllt noch +50 oder -50 bekommen, je nachdem ob sie Bob besiegt haben?

**Comment by m1a9l9t7e** [comment]
ja auf jeden fall sollte es ne belohnung geben wenn die spieler gewinnen

**Comment by svenlr** [comment]
haben wird das jetzt ein schon?

**Comment by m1a9l9t7e** [comment]
ja, ist erledigt
