### ISSUE TITLE
gameString problem

### ISSUE THREAD

**Issue by svenlr** [Machplatzwennduunsaufderstrassesiehst/Mental#26]
loadShopString
04-19 01:20:11.637 20781-20825/de.soeiner.mental W/System.err: java.lang.ArrayIndexOutOfBoundsException: length=12; index=13
04-19 01:20:11.637 20781-20825/de.soeiner.mental W/System.err:     at de.soeiner.mental.Shop.loadShopString(Shop.java:114)
04-19 01:20:11.637 20781-20825/de.soeiner.mental W/System.err:     at de.soeiner.mental.Player.loadGameString(Player.java:204)
04-19 01:20:11.637 20781-20825/de.soeiner.mental W/System.err:     at de.soeiner.mental.Player.processData(Player.java:157)
04-19 01:20:11.637 20781-20825/de.soeiner.mental W/System.err:     at de.soeiner.mental.ClientConnection.onMessage(ClientConnection.java:98)
04-19 01:20:11.637 20781-20825/de.soeiner.mental W/System.err:     at de.soeiner.mental.Server.onMessage(Server.java:49)
04-19 01:20:11.637 20781-20825/de.soeiner.mental W/System.err:     at org.java_websocket.server.WebSocketServer.onWebsocketMessage(WebSocketServer.java:484)
04-19 01:20:11.637 20781-20825/de.soeiner.mental W/System.err:     at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:375)
04-19 01:20:11.637 20781-20825/de.soeiner.mental W/System.err:     at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:158)
04-19 01:20:11.637 20781-20825/de.soeiner.mental W/System.err:     at org.java_websocket.server.WebSocketServer$WebSocketWorker.run(WebSocketServer.java:702)

**Comment by m1a9l9t7e** [comment]
fixed
