### ISSUE TITLE
branch zum testen des TrainGMs

### ISSUE THREAD

**Issue by svenlr** [Machplatzwennduunsaufderstrassesiehst/Mental#34]
könntest du das, was du jetzt in den letzten tagen alles gefixt und gemacht hast mal in eine branch hochladen? dann kann ich auch damit testen, um mir mal nen überblick über das aussehen der ganzen befehle zu verschaffen

**Comment by m1a9l9t7e** [comment]
wieso in eine branch ?

**Comment by m1a9l9t7e** [comment]
ist erstellt

**Comment by svenlr** [comment]
hm, also nach showExercises kommt nicht mehr

**Comment by m1a9l9t7e** [comment]
benutzt du die erste oder die zweite version ?
die zweite ist wie ich geschrieben habe ja irgendwie broken

Am Freitag, 6. Mai 2016 schrieb Sven L :
