### ISSUE TITLE
TrainGame hat einen Delay beim Beenden

### ISSUE THREAD

**Issue by svenlr** [Machplatzwennduunsaufderstrassesiehst/Mental#47]
Reproduzieren durch:
1. TrainGame starten
2. Seite neuladen
3. Versuchen wieder irgendwas zu starten
4. Es dauert etwas bis man wieder beitreten kann

Kein gravierender Fehler, fällt auch nicht auf. Aber bevor wir die Möglichkeit bereitstellen wollen, manuell auch aus dem Spiel zu gehen (ohne F5), sollte das eventuell behoben werden?

**Comment by m1a9l9t7e** [comment]
sollte behoben sein.
