### ISSUE TITLE
Weitere Ideen?

### ISSUE THREAD

**Issue by svenlr** [Machplatzwennduunsaufderstrassesiehst/Mental#7]
- den Server mit dem Button InApp wahlweise starten
- den Browser mit der richtigen Adresse auch InApp starten?
- statt eines Timeouts für das Scoreboard so eine Art bereit einführen (+ evtl Voting?)
- mit der Bestätigung der Antwort die bekommenen Punkte mitschicken
- bei falschen Antworten mehr abziehen, je leichter desto mehr?

**Comment by svenlr** [comment]
haben es ja jetzt auf nem funktionierenden level, jetzt können wir halt überlegen, was wir noch hinzufügen so

**Comment by m1a9l9t7e** [comment]
alles davon ist eigentlich eingebaut, bis auf das Punkte abzeihen je nach schwierigkeitsgrad. Ich weiß aber eh nicht ob das so ne gute idee ist weil man sich in 90% der fälle einfach nur vertippt. Warum sollte man dann je nach schwierigkeitsgrad punkte abgezogen bekommen ? jedenfalls geht mir das so.
Bei nem Game Mode bei dem man wirklich raten könnte wäre es vielleicht eher sinvoll
